"""fix tables

Revision ID: 2260237cbf8d
Revises: f0770ea40df7
Create Date: 2024-05-24 00:19:21.475317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2260237cbf8d"
down_revision: Union[str, None] = "f0770ea40df7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "userstrikes", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userstrikes", type_="foreignkey")

    # ### end Alembic commands ###
